# To generate the client:
# openapi-generator generate -g csharp-netcore -i firefly-iii-0.10.4.yaml -c openapi-dotnet.yaml -o generated/ -t .\api-template\

packageName: FireflyIII
packageVersion: 0.1.0
packageGuid: "FAE04EC0-301F-11D3-BF4B-00C04F79EFBC"
targetFramework: netstandard2.0
